const fs = require('fs');
const path = require('path');
const { withDangerousMod, withGradleProperties } = require('expo/config-plugins');

const JVMARGS_KEY = 'org.gradle.jvmargs';
const IPV4_FLAG = '-Djava.net.preferIPv4Stack=true';

// Forces the Gradle daemon onto a JDK < 24. JDK 24+ emits
// "WARNING: A restricted method in java.lang.System has been called" which AGP's
// prefab/CMake configure step (:react-native-worklets:configureCMakeDebug) treats
// as a fatal error. Android Studio regenerates this file on sync, so we recreate
// it after every prebuild.
const DAEMON_JVM_REL = path.join('gradle', 'gradle-daemon-jvm.properties');

// Temurin JDK 17 package ids on api.foojay.io (hotspot, ga, non-musl).
const FOOJAY_IDS = {
  'FREE_BSD.AARCH64': '8b67c80125e941a0dbe0b7cffb8aae48',
  'FREE_BSD.X86_64': 'bac3967963512d0651faeaa3b46c7bb7',
  'LINUX.AARCH64': '8b67c80125e941a0dbe0b7cffb8aae48',
  'LINUX.X86_64': 'bac3967963512d0651faeaa3b46c7bb7',
  'MAC_OS.AARCH64': '235d1c3a369f41e4d8febd9551c4e63b',
  'MAC_OS.X86_64': '8301b7daa55aaaa7ac19f37ce89e3668',
  'UNIX.AARCH64': '8b67c80125e941a0dbe0b7cffb8aae48',
  'UNIX.X86_64': 'bac3967963512d0651faeaa3b46c7bb7',
  'WINDOWS.X86_64': 'cfc837d689e6ad2bd65c51776cd1a4e3',
};

const DAEMON_JVM_CONTENT = [
  '# This file is generated by plugins/withAndroidBuildSetup.js',
  '# Prevent the JDK 24+ restricted-System-method crash in the react-native-worklets prefab CMake step.',
  ...Object.entries(FOOJAY_IDS).map(
    ([platform, id]) => `toolchainUrl.${platform}=https\\://api.foojay.io/disco/v3.0/ids/${id}/redirect`
  ),
  'toolchainVersion=17',
  '',
].join('\n');

function upsertProperty(properties, key, value) {
  const existing = properties.find((item) => item.type === 'property' && item.key === key);
  if (existing) {
    if (!existing.value.includes(IPV4_FLAG)) {
      existing.value = existing.value.trim() + ' ' + IPV4_FLAG;
    }
  } else {
    properties.push({ type: 'property', key, value });
  }
}

const withDaemonJvmCriteria = (config) =>
  withDangerousMod(config, ['android', (config) => {
    const target = path.join(config.modRequest.platformProjectRoot, DAEMON_JVM_REL);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, DAEMON_JVM_CONTENT);
    return config;
  }]);

const withAndroidBuildSetup = (config) => {
  config = withGradleProperties(config, (config) => {
    upsertProperty(
      config.modResults,
      JVMARGS_KEY,
      `-Xmx2048m -XX:MaxMetaspaceSize=512m ${IPV4_FLAG}`
    );
    return config;
  });
  return withDaemonJvmCriteria(config);
};

module.exports = withAndroidBuildSetup;